apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consumidor-ingress
  namespace: clientes
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /consumidor
            pathType: Prefix
            backend:
              service:
                name: cliente-consumidor
                port:
                  number: 80