apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clientes-ingress
  namespace: clientes
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /clientes
            pathType: Prefix
            backend:
              service:
                name: cliente-microservicio
                port:
                  number: 80