apiVersion: v1
kind: Service
metadata:
  name: cliente-microservicio
  namespace: clientes
spec:
  type: ClusterIP
  selector:
    app: cliente-microservicio
  ports:
    - name: clientes
      port: 80
      targetPort: 8080

